# generated by datamodel-codegen:
#   filename:  api.json
#   timestamp: 2025-06-07T09:46:18+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Data(BaseModel):
    data: Optional[str] = None


class Links(BaseModel):
    self: Optional[str] = None


class SelfLink(BaseModel):
    links: Optional[Links] = None


class Links1(BaseModel):
    collection: Optional[str] = None


class CollectionLink(BaseModel):
    links: Optional[Links1] = None


class Model(Data, SelfLink, CollectionLink):
    pass
