# generated by datamodel-codegen:
#   filename:  api_workaround.json
#   timestamp: 2025-06-07T09:56:45+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel


class Data(BaseModel):
    data: Optional[str] = None


class Links(BaseModel):
    self: Optional[str] = None


class SelfLink(BaseModel):
    links: Optional[Links] = None


class Links1(BaseModel):
    collection: Optional[str] = None


class CollectionLink(BaseModel):
    links: Optional[Links1] = None


class Workaround(Data, SelfLink, CollectionLink):
    links: Optional[Dict[str, Any]] = None
